### PR TITLE
add variable enableMathJax and fix a build error.

### PR DESCRIPTION
**Pull request by cntrump**
1. add variable enableMathJax

2. fix hugo build error:
execute of template failed: template: index.html:32:22: executing "main" at <.RelPermalink>: can't evaluate field RelPermalink in type *page.Pager.

### CODE REVIEW

**Comment by qqhann** [comment]
Thanks for your PR, @cntrump !

- What Hugo version are you using?
Because I don't see the build error. 🤔 

- Why do you want to have an option to disable mathjax? Does it slow your site?

**Comment by cntrump** [comment]
> Thanks for your PR, @cntrump !
> 
> * What Hugo version are you using?
>   Because I don't see the build error. 🤔
> * Why do you want to have an option to disable mathjax? Does it slow your site?

thanks your theme. 😄
I  just write some codes and highlight with css.
I am looking a simple theme for  loading fast.

now I finish a theme without js: [hugo-notepadium](https://github.com/cntrump/hugo-notepadium)

**Comment by qqhann** [comment]
Good for you.


Your mathjax update is problematic because it will change existing users' behavior. 
I've updated it to set default to true.

**Comment by qqhann** [comment]
Also, even when you fork, please checkout branch when opening PR.
That will make things easier for original owners.

**Pull request merged**
